spring:
  datasource:
    password: ${DB_ROOT_PASSWORD}

jwt:
  # jwt secret key
  secret: ${JWT_SECRET}

app:
  token-encryption:
    secret: ${TOKEN_ENCRYPTION_SECRET}

oauth:
  google:
    client-secret: ${GOOGLE_CLIENT_SECRET}

  kakao:
    client-secret: ${KAKAO_CLIENT_SECRET}
