spring:
  datasource:
    # 로컬 MySQL 연결 설정
    url: jdbc:mysql://localhost:3306/${DB_NAME}?useUnicode=true&serverTimezone=Asia/Seoul
    username: root

oauth:
  # google 소셜 로그인 정보
  google:
    redirect-uri: http://localhost:8080/api/auth/callback/GOOGLE
    authorization-params:
      access_type: offline
      prompt: consent

  # kakao 소셜 로그인 정보
  kakao:
    redirect-uri: http://localhost:8080/api/auth/callback/KAKAO

server:
  env: local
  port: 8080
  serverAddress: localhost

serverName: local_server

app:
  cookie:
    secure: false
  openapi:
    server-uri: http://localhost:8080
  redirect:
    # local test를 위한 uri이기 때문에 port를 3000으로 설정
    onboarding-uri: http://localhost:3000/onboarding
    login-success-uri: http://localhost:3000/oauth/callback?status=LOGIN_SUCCESS
    login-failure-uri: http://localhost:3000/oauth/callback?status=LOGIN_FAILED
