spring:
  datasource:
    # Docker Compose 배포 시 MySQL 서비스명(db)으로 연결
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useUnicode=true&serverTimezone=Asia/Seoul
    username: ${DB_USER}

oauth:
  # google 소셜 로그인 정보
  google:
    redirect-uri: ${API_SERVER_URL}/api/auth/callback/GOOGLE

  # kakao 소셜 로그인 정보
  kakao:
    redirect-uri: ${API_SERVER_URL}/api/auth/callback/KAKAO

server:
  env: blue
  port: 8080
  serverAddress: 43.201.237.252

serverName: blue_server

app:
  cors:
    allowed-origins:
      - ${FRONTEND_URL}
  openapi:
    server-uri: ${API_SERVER_URL}
  redirect:
    onboarding-uri: ${FRONTEND_URL}/onboarding
    login-success-uri: ${FRONTEND_URL}/oauth/callback?status=LOGIN_SUCCESS
    login-failure-uri: ${FRONTEND_URL}/oauth/callback?status=LOGIN_FAILED
