spring:
  config:
    import:
    - optional:file:.env[.properties]
    - optional:file:.env.local[.properties]
  profiles:
    active: local
    group:
      local: common, secret
      blue: common, secret
      green: common, secret

server:
  env: blue
